// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TableOutlined from '/Users/oliverke/work/echo/frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
import SmileOutlined from '/Users/oliverke/work/echo/frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/Users/oliverke/work/echo/frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { TableOutlined, SmileOutlined, CrownOutlined };
